import { Inter } from 'next/font/google';
import { Montserrat } from 'next/font/google';

import { Nav } from '../components/nav';
import './global.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});

export const metadata = {
  title: 'Welcome to online-store',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-pampas-100 ${inter.variable} ${montserrat.variable}`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
