name: CI
on:
  push:
  pull_request:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  track-nx:
    name: Track NX
    runs-on: ubuntu-latest
    steps:
      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
  main:
    runs-on: ubuntu-latest
    steps:
      - run: yarn nx affected -t lint,test,build --parallel=3
      - run: yarn nx affected -t e2e --parallel=1
